spring.application.name=EMS

spring.datasource.url=jdbc:mysql://localhost:3306/ems_db
spring.datasource.username=root
spring.datasource.password=@Sahil123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true